sudo: required
dist: trusty
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - zsync
    - squashfs-tools
services:
- docker

env:
  - RECIPE=leafpad

script:
- bash -e travis.sh $RECIPE
- FILES=$(find out/ -name "*.AppImage")
- bash -e bintray.sh $FILES 

notifications:
  irc:
    channels: 
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
