sudo: false
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - zsync
services:
- docker

env:
#  - RECIPE=scribus
  - RECIPE=subsurface
#  - RECIPE=firefox
#  - RECIPE=arduino
#  - RECIPE=libreoffice
#  - RECIPE=vlc
#  - RECIPE=leafpad
#  - RECIPE=chromium

script:
- bash travis.sh $RECIPE
- find out/ -name "*.AppImage" -exec bash bintray.sh {} \; 
